[project]
name = "cell-interactome"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
dev-dependencies = []

# [tool.uv.sources]
# dinov2 = { git = "https://github.com/kirchhausenlab/dinov2.git" }
# uv pip install git+https://github.com/kirchhausenlab/dinov2.git#egg=dinov2[extras]
