seed: 42
output_base: /nfs/scratch2/shared_image_recog/
output_dir: ${output_base}/LiFT
model_type: dino3d
is_dino3d: true

model:
  lr: 0.0001
  batch_size: 64
  stride: 4
  embed_dim: 1024
  patch_size: 16
  imsize: [64, 256, 256]
  augment: true
  loss_type: cosine
  dataroot: /nfs/scratch2/shared_image_recog_ml/dino3d_auto_crop_sep_ibot_head/weights/step=3999.pth
  in_chans: 1
  train:
    output_dir: ${output_dir}/weights
    ckpt_path: ""
    resume: false

num_workers: 8
dataset:
  transforms:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.2
  base_data_dir: /nfs/scratch2/shared_image_recog_ml/llsm_3d_ds_auto_crop
  path_to_txt: /nfs/scratch2/shared_image_recog_ml/llsm_3d_ds_auto_crop/data_paths_3D.txt
  max_files: 100000

train:
  start_epoch: 0
  epochs: 10000
  max_steps: 625000

student:
  freeze_backbone: false
  arch: vit_large
  in_chans: 1
  patch_size: 16
  drop_path_rate: 0.4
  layerscale: 1.0e-05
  drop_path_uniform: true
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  ffn_layer: swiglufused
  num_register_tokens: 4
  block_chunks: 0
  interpolate_antialias: false
  interpolate_offset: 0.1

experiment_name: LiFT
experiment_logger:
  _target_: cell_interactome.logging.experiment_loggers.WandbExperimentLogger
  project: cell-interactome
  entity: artificial-intelligence-research
  name: ${experiment_name}
  resume: false

logging:
  log_interval: 10
  save_interval: 1000
  pred_interval: 10
  num_pca_images: 8
  num_pred_images: 1

sampler:
  sampler_type:
    _target_: cell_interactome.data.dino3d.dataloaders.SamplerType
    _args_:
      - 3
  size: -1
  advance: 0
  shuffle: true
  seed: ${seed}
