seed: 42
output_base: /nfs/scratch2/shared_image_recog/
output_dir: ${output_base}/LiFT
model_type: dino3d
is_dino3d: true

model:
  lr: 0.0001
  batch_size: 64
  save_every: 1000
  stride: 4
  patch_size: 16
  imsize: 448
  augment: true
  loss_type: cosine
  dataroot: /nfs/scratch2/shared_image_recog_ml/dino3d_auto_crop_sep_ibot_head/weights/step=3999.ckpt
  channel: None

device: cuda
num_workers: 32
dataset:
  transforms:
    brightness: 0.2
    contrast: 0.2
    saturation: 0.2
    hue: 0.2
  base_data_dir: ""
  path_to_txt: ""
  max_files: 1000

train:
  start_epoch: 0
  epochs: 10000
