use_fp16: true
sharding_strategy: SHARD_GRAD_OP
dtype: bf16
mixed_precision:
  param_dtype: bf16
  reduce_dtype: bf16
  buffer_dtype: fp32
teacher:
  backbone:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: bf16
      buffer_dtype: fp32
  dino_head:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: bf16
      buffer_dtype: fp32
  ibot_head:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: bf16
      buffer_dtype: fp32
  desd_head:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: bf16
      buffer_dtype: fp32
  sfp:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: bf16
      buffer_dtype: fp32
  rotation_head:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: bf16
      buffer_dtype: fp32
  reconstruction:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: bf16
      buffer_dtype: fp32
student:
  backbone:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: bf16
      buffer_dtype: fp32
  dino_head:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: fp32
      buffer_dtype: fp32
  ibot_head:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: fp32
      buffer_dtype: fp32
  desd_head:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: fp32
      buffer_dtype: fp32
  sfp:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: fp32
      buffer_dtype: fp32
  rotation_head:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: fp32
      buffer_dtype: fp32
  reconstruction:
    sharding_strategy: SHARD_GRAD_OP
    mixed_precision:
      param_dtype: bf16
      reduce_dtype: fp32
      buffer_dtype: fp32
