experiment_name: vits8-mlp-pretrain-sknopp-8_local_crops-minmr_0.1-maxmr_0.5-block_mask-32k_prototypes-resize_112_48-teacher_temp_0.07-flip-rot_no-pos-emb-bs_336
ckpt_step: 249999
backbone_path: /raid3/shared_image_recog_ml/output/${experiment_name}/checkpoints/step=${ckpt_step}/backbone.pth # step=249999 for 250k steps, step=140999 for 150k steps
seed: 0
file_path: null
save_path: null
file_start: 0
file_end: null
global_hist_min: null
global_hist_max: null
model: vits8
num_tt_register_tokens: 1

device_type: "cuda"
dtype: "bf16"
use_amp: true
find_unused_parameters: false # Distributed DDP find unused parameters
distributed: true
backend: "cpu:gloo,cuda:nccl"

batch_size: 1
num_workers: 4
pin_mem: true # Pin CPU memory in DataLoader
persistent_workers: true

upsample_factor: 3.0
chunk_size: [8,8,8]
isotropic_scale_factor: [1.0, 1.0, 1.0] # use e.g. [2.404, 1.0, 1.0] if data is anisotropic
crop_params: [0, 0, 0, 0, 0, 0] # (z_start, z_end, y_start, y_end, x_start, x_end) - when [0,0,0,0,0,0], uses full volume
norm_feat: norm
chunk_interpolate: true
interpolate_volume_chunk_size: [1, 448, 448, 448]

inference_route: "streaming" # "default" or "streaming"

streaming_storage: "gpu" # "gpu", "cpu", or "disk"
streaming_q_block_tokens: 16384
streaming_patch_chunk_size: [224,448,448] # when null, uses vol_metadata["chunk_size"]
streaming_pin_memory: true
streaming_kv_storage: "gpu" # "gpu", "cpu", or "disk"

streaming_use_triton: true
streaming_triton_block_m: 128
streaming_triton_block_n: 256
streaming_triton_block_d: 64
streaming_triton_num_warps: 4
streaming_triton_num_stages: 3
