defaults:
  - ssl_default_config
  - model: vitl14
  - _self_

base_path: /nfs/scratch2/shared_image_recog_ml

MODEL:
  WEIGHTS: ${base_path}/weights/dinov2/pretrained/dinov2_vitl14_reg4_pretrain.pth

train:
  dataset_path: ${base_path}/llsm_224
  path_to_txt: ${train.dataset_path}/train.txt
  output_dir: ${base_path}/weights/dinov2/llsm_224
