defaults:
  - model: vitg14_reg4
  - ddp: fsdp
  - optim: adamw
  - train: vitg14_reg4
  - logging: wandb
  - _self_

seed: 0
base_path: /nfs/scratch2/shared_image_recog_ml
weights_path: ${base_path}/weights/dinov2
TARGET_FILE_EXTENSION: ".pth"
search_suffix: "2D/**/*${TARGET_FILE_EXTENSION}"
max_files: 100000

logging:
  use_wandb: true
  wandb_config:
    name: heads_pretrain
  log_preds: true
  log_pred_steps: 100
  num_images: 5
  test_dataset_path: ${base_path}/llsm_518

train:
  dataset_path: ${base_path}/llsm_518
  path_to_txt: ${train.dataset_path}/train.txt
  output_dir: ${base_path}/weights/dinov2/llsm_518
  search_suffix: ${search_suffix}
  max_files: ${max_files}

test:
  dataset_path: ${base_path}/llsm_full_res
  path_to_txt: ${test.dataset_path}/test.txt
  search_suffix: ${search_suffix}
  max_files: ${max_files}

model:
  weights: ${weights_path}/llsm_518/ckpt_step_99.pth

evaluation:
  eval_period_steps: 100
