defaults:
  - model/train: vitb8_reg4
  - model/inference: vitb8_reg4
  - training/distributed: fsdp
  - training/optim: adopt
  - training/scheduler: cosine_3d
  - logging: wandb
  - data/collate_fn: collate_3d
  - data/dataloader: base_web_3d
  - data/dataset: cell_web_dataset_3d
  - data/transforms: dino_3d
  - _self_

seed: 0
base_path: /raid3/shared_image_recog_ml
experiment_name: dino3d_vitb8_reg4_desd_smaller_crops_improved_mask_vae_recon_1

shards:
  train:
    - /raid1/shared_image_recog_ml/llsm_3d_ds_auto_crop/dataset-{000000..000868}.tar
    - /raid2/shared_image_recog_ml/llsm_3d_ds_auto_crop/dataset-{000000..000778}.tar
    - /raid3/shared_image_recog_ml/llsm_3d_ds_auto_crop/dataset-{000000..000768}.tar
  test:
    - /raid1/shared_image_recog_ml/llsm_3d_ds/dataset-{000000..000919}.tar

data:
  dataset:
    train_dataset:
      base_data_dir: "${shards.train[0]}::${shards.train[1]}::${shards.train[2]}"
    test_dataset:
      base_data_dir: "${shards.test[0]}"

model:
  train:
    output_dir: ${base_path}/weights/${experiment_name}
    ckpt_dir: "" # ${model.train.output_dir}
    resume: false
  inference:
    weights_path: ${base_path}/weights/${experiment_name}/step=3999.ckpt/teacher_weights.pth

inference:
  save_dir: ${base_path}/preds/${experiment_name}
