defaults:
  - data/dataloader: base_web_3d # base_3d
  - data/dataset: cell_web_dataset_3d # cell_dataset_3d
  - data/collate_fn: collate_3d
  - data/transforms: dino_3d
  - training/optim: adopt
  - training/scheduler: cosine_3d_lift
  - _self_

seed: 42
output_base: /nfs/scratch2/shared_image_recog_ml
output_dir: ${output_base}/LiFT/backbone_vitg_16_reg4_desd_loss
model_type: dino3d
is_dino3d: true

training:
  use_additional_params: False
  add_scheduler: False
  start_epoch: 0
  max_steps: 100000

model:
  norm: true
  display_lr_feats: true
  stride: 16
  embed_dim: 1536
  patch_size: 16
  imsize: [64, 256, 256]
  global_crops: [48, 224, 224]
  loss_type: cosine
  dataroot: /nfs/scratch2/shared_image_recog_ml/weights/dino3d_vitg16_reg4_desd_loss/step=28999.ckpt/teacher_weights.pth
  in_chans: 1
  train:
    output_dir: ${output_dir}/weights
    ckpt_path: ""
    resume: false
    max_steps: ${training.max_steps}

student:
  arch: vit_giant2
  in_chans: 1
  patch_size: 16
  drop_path_rate: 0.4
  layerscale: 1.0e-05
  drop_path_uniform: true
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  ffn_layer: swiglufused
  num_register_tokens: 4
  block_chunks: 0
  interpolate_antialias: false
  interpolate_offset: 0.1

experiment_name: LiFT
logging:
  log_interval: 10
  save_interval: 1000
  pred_interval: 20 # test
  num_pca_images: 4
  num_pred_images: 1
  project: cell-interactome
  entity: artificial-intelligence-research
  name: ${experiment_name}
  resume: false

shards:
  train:
    - /raid1/shared_image_recog_ml/llsm_3d_ds_auto_crop/dataset-{000000..000868}.tar
    - /raid2/shared_image_recog_ml/llsm_3d_ds_auto_crop/dataset-{000000..000778}.tar
    - /raid3/shared_image_recog_ml/llsm_3d_ds_auto_crop/dataset-{000000..000768}.tar
  test:
    # - /raid1/shared_image_recog_ml/llsm_3d_ds/dataset-{000000..000919}.tar
    - /raid3/llsm_lift/dataset-{000000..000034}.tar

data:
  dataset:
    train_dataset:
      # base_data_dir: "${shards.train[0]}::${shards.train[1]}::${shards.train[2]}"
      base_data_dir: "${shards.train[2]}"
      # nodesplitter:
      #   _partial_: true
      #   _target_: cell_interactome.data.dino3d.dataset.custom_split_by_node
      #   node_file_counts: [869, 779, 769]
    test_dataset:
      base_data_dir: ${shards.test[0]}
      # base_data_dir: ${output_base}/llsm_3d_ds
