defaults:
  - data/dataloader: base_web_3d # base_3d
  - data/dataset: cell_web_dataset_3d # cell_dataset_3d
  - _self_

seed: 42
output_base: /nfs/scratch2/shared_image_recog_ml
output_dir: ${output_base}/LiFT
model_type: dino3d
is_dino3d: true

training:
  use_additional_params: True
  add_scheduler: True
  optim:
    config:
      lr: 0.0
      base_lr: 1.0e-04
      amsgrad: True
      weight_decay: 1e-06
      scheduler:
        mode: min
        patience: 500
        factor: 0.3
        threshold_mode: "rel"
        cooldown: 20
        min_lr: 1.0e-06
  start_epoch: 0
  max_steps: 200000

model:
  display_lr_feats: True
  stride: 8
  embed_dim: 384
  patch_size: 8
  imsize: [64, 256, 256]
  loss_type: cosine
  dataroot: /nfs/scratch2/shared_image_recog_ml/dino3d_vits8_reg4/weights/'step=24999.ckpt'
  in_chans: 1
  train:
    output_dir: ${output_dir}/weights
    ckpt_path: ""
    resume: false

train:

student:
  arch: vit_small
  in_chans: 1
  patch_size: 8
  drop_path_rate: 0.4
  layerscale: 1.0e-05
  drop_path_uniform: true
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  ffn_layer: swiglufused
  num_register_tokens: 4
  block_chunks: 0
  interpolate_antialias: false
  interpolate_offset: 0.1

experiment_name: LiFT
logging:
  log_interval: 10
  save_interval: 1000
  pred_interval: 250 # 250
  num_pca_images: 8
  num_pred_images: 1
  project: cell-interactome
  entity: artificial-intelligence-research
  name: ${experiment_name}
  resume: false

data:
  chunk_1: "/nfs/scratch/shared_image_recog_ml/llsm_3d_ds_auto_crop_sharded/dataset-{000000..000119}.tar"
  chunk_2: "/nfs/scratch1/shared_image_recog_ml/llsm_3d_ds_auto_crop_sharded/dataset-{000120..000239}.tar"
  chunk_3: "/nfs/scratch2/shared_image_recog_ml/llsm_3d_ds_auto_crop_sharded/dataset-{000240..000359}.tar"
  dataset:
    train_dataset:
      base_data_dir: ${data.chunk_1}::${data.chunk_2}::${data.chunk_3}
    test_dataset:
      base_data_dir: ${output_base}/llsm_3d_ds
