ckpt_dir: "/nfs/scratch2/shared_image_recog_ml/weights/dino3d_vits8_reg4_higher_lr/step=24999.ckpt/teacher_weights.pth"

student:
  freeze_backbone: true
  arch: vit_base
  patch_size: 8
  drop_path_rate: 0.4
  layerscale: 1.0e-05
  drop_path_uniform: true
  qkv_bias: true
  proj_bias: true
  ffn_bias: true
  ffn_layer: swiglufused
  num_register_tokens: 4
  block_chunks: 0
  interpolate_antialias: false
  interpolate_offset: 0.1

teacher:
  momentum_teacher: 0.994
  final_momentum_teacher: 1
  warmup_teacher_temp: 0.04
  teacher_temp: 0.07
  warmup_teacher_temp_steps: 37500

crops:
  global_crops_size: ${model.train.crops.global_crops_size}
  local_crops_size: ${model.training.crops.local_crops_size}
