max_steps: 625000
weight_decay: 0.04
weight_decay_end: 0.2
base_lr: 2.0e-04 # learning rate for a batch size of 1024
lr: 0.0 # will be set after applying scaling rule
warmup_steps: 100000
min_lr: 1.0e-06
clip_grad: 3.0
freeze_last_layer_steps: 1250
scaling_rule: sqrt_wrt_1024
patch_embed_lr_mult: 0.2
layerwise_decay: 1.0
adamw_beta1: 0.9
adamw_beta2: 0.999
