experiment_logger:
  _target_: cell_interactome.logging.experiment_loggers.WandbExperimentLogger
  project: cell-interactome
  entity: artificial-intelligence-research
  name: ${experiment_name}
  resume: false

log_interval: 10
save_interval: 1000
pred_interval: 10
num_pca_images: 8
num_pred_images: 1
