log_interval: 10
resume: true
batch_size_per_gpu: 12
num_workers: 100
max_steps: 625000
cache_dataset: true
centering: sinkhorn_knopp
dataset_path: ""
path_to_txt: ""
output_dir: "output"
max_files: 100000
